### ISSUE TITLE
Users not created in MySQL database on registration

### ISSUE THREAD

**Issue by LeviBroadnax** [SystemStack/ARM-Clicker#7]
There may be some configurations to add to the accounts-config.js file, but it may be better handled utilizing middleware in server.js to hide that layer from the client.

**Comment by SystemStack** [comment]
Solved with  #c73d30e8ec1bc190c4ae633ec53df90a95694927

**Comment by LeviBroadnax** [comment]
Solved with #9 [commit c73d30e8ec...](https://github.com/SystemStack/ARM-Clicker/pull/9/commits/c73d30e8ec1bc190c4ae633ec53df90a95694927)
